const images = [
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_001.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_002.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_009.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_011.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_014.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_015.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_016.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_017.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_018.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_019.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_020.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_021.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_022.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_023.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_024.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_025.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_026.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_027.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_028.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_029.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_030.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_031.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_032.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_033.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_034.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_035.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_036.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_037.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_038.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_039.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_040.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_041.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_042.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_043.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_044.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_045.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_046.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_047.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_048.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_049.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_050.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_051.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_052.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_053.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_054.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_055.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_056.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_059.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_060.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_061.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_062.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_063.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_064.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_065.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_066.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_067.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_068.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_069.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_070.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_071.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_072.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_073.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_074.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_075.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_076.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_077.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_078.png?raw=true',
    'https://github.com/CrypticWaffles/hdanshita/blob/main/img/sensei_079.png?raw=true'
];

function replaceImages() {
  const imgElements = document.querySelectorAll('img');
  imgElements.forEach(img => {
    const randomImage = images[Math.floor(Math.random() * images.length)];
    img.src = randomImage;
  });
}

// Run method on load
replaceImages();